### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by ManojKiranA** [supliu/laravel-graphql#2]
Can you release atleast one stable version 0.0.1 may be

**Comment by benfreke** [comment]
Agreed, but if this is ready for public consumption then I'd prefer a `1.0.0`, as per [Semver](https://semver.org/#spec-item-5).

**Comment by ManojKiranA** [comment]
then go ahed and relese the version

git tag -a 1.0.0 -m "First Vesion 1.0.0"

git push origin 1.0.0

**Comment by jansenfelipe** [comment]
Tks! Release created
